import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { getPosts, IPost } from '../libs/posts'

interface IProps {
  posts: IPost[]
}

const Home: NextPage<IProps> = ({ posts }) => {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />        
      </Head>
      <h1>DEVISTA Blog</h1>
      {/* index vai de 0 à infinito */}
      {posts.map((post, index) => (
        <Link key={index} href={`/post/${post.slug}`} >
          <a>
            <h2>{post.title}</h2>
            <p>{post.date}</p>
          </a>
        </Link>
      ))}
    </>
  )
}

export default Home


// Será lido no momento de build

export const getStaticProps: GetStaticProps = () => {
  // Ler os arquivos markdown
  const posts = getPosts()

  // retornar props
  return {
    props: {
      posts
    },
  }
}
