import type { GetStaticPaths, NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { getPostBySlug, getPostsSlugs, IPost } from '../../libs/posts'

interface IProps {
  post: IPost
}

interface IPathProps {
  params: {
    slug: string
  }
}

const Post: NextPage<IProps> = ({ post }) => {

  return (
    <>
      <Head>
        <title>Posts Page</title>
        <meta name="description" content="Generated by create next app" />        
      </Head>

      <h1>{post.title}</h1>
      <h2>{post.date}</h2>
      <article>{post.content}</article>
      <Link href="/">
        <a>
          <button>Voltar</button>
        </a>      
      </Link>
          
    </>
  )
}

export default Post

export const getStaticPaths: GetStaticPaths = () => {
  // Pegar array de slugs
  const slugs = getPostsSlugs()
  const formattedSlugs = slugs.map((slug) => ({
    params: {
      slug
    },
  }))

  // retornar array
  return {
    paths: formattedSlugs,
    fallback: true,
  }
}


// Será lido no momento de build

export const getStaticProps = ({ params }: IPathProps) => {
  const slug = params.slug

  // Procurar post através do slug
  const post = getPostBySlug(slug)

  // retornar post
  return {
    props: {
      post,
    },
  }
}
